
version: "3"
services:
  #  Container for Java
  #  docker run -d --name track-service-java -p 8080:8080 -network host spring-boot-java
  track-service:
    build: track-service/.
    container_name: track-service-Mongo
    ports:
      - '8082:8082'

  #  Container for Mongo
  # docker run -d --name track-service-mongo -p 27017 -network host mongo
  api-gateway:
    build: api-gateway/.
    container_name: api-gateway
    ports:
      - '8090:8090'


  config-server:
    build: config-server/.
    container_name: config-server
    ports:
      - '8891:8891'

  eureka-server:
    build: eureka-server/.
    container_name: eureka-server
    ports:
      - '8080:8080'

  user-service:
    build: user-service/.
    container_name: user-service
    ports:
      - '8081:8081'


